In [1]:
import numpy as np

In [59]:
"""Arithmetic operations."""
import numpy as np

def test_run():
    a = np.array([(1, 2, 3, 4, 5), (10, 20, 30, 40, 50)])
    print "Original array a:\n", a
    
    # Multiply a by 2
    print "\nMultiply a by 2:\n", 2*a
    
    # Divide a by 2
    print "\nDivide a by 2:\n", a/2
    print "\nDivide a by 2.0:\n", a/2.0
    
    b = np.array([(100, 200, 300, 400, 500), (1, 2, 3, 4, 5)])
    print "\nOriginal array b:\n", b
    
    # Add the two arrays
    print "\nAdd a + b:\n", a + b
    
    # Multiply the two arrays
    print "\nMultiply a and b:\n", a*b
    
    # Divide the two arrays
    print "\nDivide a and b:\n", a/b
    
    
    
test_run()

Original array a:
[[ 1  2  3  4  5]
 [10 20 30 40 50]]

Multiply a by 2:
[[  2   4   6   8  10]
 [ 20  40  60  80 100]]

Divide a by 2:
[[ 0  1  1  2  2]
 [ 5 10 15 20 25]]

Divide a by 2.0:
[[  0.5   1.    1.5   2.    2.5]
 [  5.   10.   15.   20.   25. ]]

Original array b:
[[100 200 300 400 500]
 [  1   2   3   4   5]]

Add a + b:
[[101 202 303 404 505]
 [ 11  22  33  44  55]]

Multiply a and b:
[[ 100  400  900 1600 2500]
 [  10   40   90  160  250]]

Divide a and b:
[[ 0  0  0  0  0]
 [10 10 10 10 10]]


In [52]:
"""Accessing elements #4 """
import numpy as np
def test_run():
    a = np.array([(20, 25, 10, 23, 26, 32, 10, 5, 0), (0, 2, 50, 20, 0, 1, 28, 5, 0)])
    print a
    
    # calculating mean
    mean = a.mean()
    print mean
    
    # masking
    print a[a<mean]
    
    a[a<mean] = mean
    print a
    
test_run()

[[20 25 10 23 26 32 10  5  0]
 [ 0  2 50 20  0  1 28  5  0]]
14.2777777778
[10 10  5  0  0  2  0  1  5  0]
[[20 25 14 23 26 32 14 14 14]
 [14 14 50 20 14 14 28 14 14]]


In [47]:
"""Accessing elements #3 """
import numpy as np
def test_run():
    a = np.random.rand(5)
    print a
    
    #accessing using list of indices
    indices = np.array([1, 1, 2, 3])
    print a[indices]
    
test_run()

[ 0.94573632  0.18445554  0.85068615  0.09467445  0.7819472 ]
[ 0.18445554  0.18445554  0.85068615  0.09467445]


In [ ]:
"""Accessing array elements. #2 """
import numpy as np

def test_run():
    a = np.random.rand(5, 4)
    print "Array:\n", a
    
    # Accessing element at position (3, 2)
    element = a[3, 2]
    print element
    
    # Elements in defined range
    print a[0, 1:3]
    print a[0:2, 0:2]
    print a[:, 0:3:2] # will select columns 0, 2 for every row
    
test_run()

In [44]:
"""Accessing array elements. #1 """
import numpy as np

def test_run():
    a = np.random.rand(5, 4)
    print "Array:\n", a
    
    # Assigning a value to a particular location
    a[0, 0] = 1
    print "\nModified (replaced one element):\n", a
    a[0, :] = 2
    print "\nModified (replaced one element):\n", a
    a[:, 3] = [1, 2, 3, 4, 5]
    print "\nModified (replaced one element):\n", a

test_run()

Array:
[[ 0.37754032  0.49182432  0.29573844  0.16164786]
 [ 0.75106851  0.31369312  0.62061538  0.32400708]
 [ 0.57037186  0.10121704  0.45555342  0.37046722]
 [ 0.52318449  0.13011157  0.40803274  0.92571757]
 [ 0.85906333  0.87390795  0.27972161  0.85634816]]
0.408032739208
[ 0.49182432  0.29573844]
[[ 0.37754032  0.49182432]
 [ 0.75106851  0.31369312]]
[[ 0.37754032  0.29573844]
 [ 0.75106851  0.62061538]
 [ 0.57037186  0.45555342]
 [ 0.52318449  0.40803274]
 [ 0.85906333  0.27972161]]

Modified (replaced one element):
[[ 1.          0.49182432  0.29573844  0.16164786]
 [ 0.75106851  0.31369312  0.62061538  0.32400708]
 [ 0.57037186  0.10121704  0.45555342  0.37046722]
 [ 0.52318449  0.13011157  0.40803274  0.92571757]
 [ 0.85906333  0.87390795  0.27972161  0.85634816]]

Modified (replaced one element):
[[ 2.          2.          2.          2.        ]
 [ 0.75106851  0.31369312  0.62061538  0.32400708]
 [ 0.57037186  0.10121704  0.45555342  0.37046722]
 [ 0.52318449  0.13011157  0

In [38]:
"""How fast is NumPy?"""
import numpy as np
from time import time

def how_long(func, *args):
    """Execute function with given arguments, and measure execution time."""
    t0 = time()
    result = func(*args) # all arguments are passed in as-is
    t1 = time()
    return result, t1 - t0

def manual_mean(arr):
    """Compute mean (average) of all elements in the given 2D array."""
    sum = 0
    for i in xrange(0, arr.shape[0]):
        for j in xrange(0, arr.shape[1]):
            sum = sum + arr[i, j]
    return sum / arr.size

def numpy_mean(arr):
    """Compute mean (average) using NumPy."""
    return arr.mean()

def test_run():
    """Function called by Test Run."""
    nd1 = np.random.random((1000, 10000))
    
    # Time the two functions, retrieving results and execution times
    res_manual, t_manual = how_long(manual_mean, nd1)
    res_numpy, t_numpy = how_long(numpy_mean, nd1)
    print "Manual: {:.6f} ({:.3f} secs.) vs Numpy: {:.6f} ({:.3f} secs.)".format(res_manual, t_manual, res_numpy, t_numpy)
    
    # Make sure both give us the same answer (upto some precision)
    assert abs(res_manual - res_numpy) <= 10e-6, "Results aren't equal!"
    
    # Compute speedup
    speedup = t_manual / t_numpy
    print "NumPy mean is ", speedup, "times faster than manual for loops."

test_run()

Manual: 0.500114 (1.765 secs.) vs Numpy: 0.500114 (0.010 secs.)
NumPy mean is  185.657288297 times faster than manual for loops.


In [35]:
"""Using time function."""
import time

def test_run():
    t1 = time.time()
    print "ML4T"
    t2 = time.time()
    print "The time taken by print statement is ", t2 - t1, " seconds"

test_run()

ML4T
The time taken by print statement is  2.62260437012e-05  seconds


In [33]:
def get_max_index(a):
    """Return the index of the maximum value in given 1D array."""
    # TODO: Your code here
    #return np.argmax(a)
    return a.argmax()

def test_run():
    a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
    print "Array:", a
    
    # Find the maximum and its index in array
    print "Maximum value:", a.max()
    print "Index of max:", get_max_index(a)


test_run()


Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max: 5


In [27]:
# operations on ndarrays
def test_run():
    np.random.seed(693)
    a = np.random.randint(0, 10, size=(5, 4))
    print "Array:\n", a
    
    # Sum of all elements
    print "Sum of all elements:", a.sum()
    
    # Iterate over rows, to compute sum of each column
    print "Sum of each column:\n", a.sum(axis=0)
    
    # Iterate over columns to compute sum of each row
    print "Sum of each row:\n", a.sum(axis=1)
    
    # Statistics: min, max, mean (across rows, cols, and overall)
    print "Minimum of each column:\n", a.min(axis=0)
    print "Maximum of each row:\n", a.max(axis=1)
    print "Mean of all elements:", a.mean()
    
test_run()

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of all elements: 79
Sum of each column:
[25 15 25 14]
Sum of each row:
[ 8 12 21 24 14]
Minimum of each column:
[1 0 0 1]
Maximum of each row:
[5 4 9 9 7]
Mean of all elements: 3.95


In [22]:
def array_attributes():
    # Array attributes
    a = np.random.random((5, 4))
    print a.shape[0] # number of rows
    print a.shape[1] # number of columns
    print a.size # number of elements
    print a.dtype

array_attributes()

5
4
20
float64


In [23]:
def test_run():
    print np.array([(2, 3, 4), (5, 6, 7)])
    print np.empty(5)
    print np.empty((5, 4))
    print np.ones((5, 4))
    print np.ones((5, 4), dtype=np.int_)
    print np.random.rand(5,4) # uniform distribution [0, 1)
    print np.random.normal(size=(3,4))  # mean 0, std 1
    print np.random.normal(10, 30, size=3) # mean 10, std 30
    # Random integers
    print np.random.randint(10, 30, size=3) # mean 10, std 30
    
test_run()

[[2 3 4]
 [5 6 7]]
[  0.00000000e+000   9.28188876e-317   0.00000000e+000   0.00000000e+000
   0.00000000e+000]
[[ 0.50213533  0.18027242  0.46645857  0.44808619]
 [ 0.34808517  0.50653717  0.82711359  0.89529303]
 [ 0.02684817  0.33068669  0.59958154  0.57820452]
 [ 0.2532948   0.11581983  0.53998597  0.17237983]
 [ 0.48793926  0.97751516  0.36384281  0.06607974]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 0.9087986   0.44149322  0.67587352  0.17416927]
 [ 0.87881681  0.45608087  0.88528777  0.50046219]
 [ 0.39243468  0.0932956   0.79994083  0.551996  ]
 [ 0.14015764  0.16663778  0.30330638  0.76974871]
 [ 0.84372202  0.75800847  0.40466715  0.04583874]]
[[ 0.69162362  1.95831918 -0.24122636  0.96082222]
 [ 1.11718456  1.00897951  0.09708725 -0.21744984]
 [-0.23043736 -0.89389249  0.32574022 -0.77789142]]
[ 31.54309996   7.72935523  63.83488799]
[23 16 24]
